### ISSUE TITLE
AppStore\\Jws\\Parser does not exist

### ISSUE THREAD

**Issue by jadayash** [imdhemy/laravel-in-app-purchases#177]
### Liap version(s) affected

1.3

### Description

Hello
Thanks for this great package.

Am getting this error in Laravel error log when sending a notification from App Store

[object] (ReflectionException(code: -1): Class Imdhemy\\AppStore\\Jws\\Parser does not exist

How am able to resolve this issue?

### How to reproduce

Receive a notification from App Store

**Comment by imdhemy** [comment]
Hello @jadayash 

- Can you share more information from the error stack?
- What is the output of the following command: `composer show imdhemy/appstore-iap --locked`

**Comment by jadayash** [comment]
Salam @imdhemy 
Thanks for your quick response

```
[2022-11-01 11:01:55] local.ERROR: Target class [Imdhemy\AppStore\Jws\Parser] does not exist. {"exception":"[object] (Illuminate\\Contracts\\Container\\BindingResolutionException(code: 0): Target class [Imdhemy\\AppStore\\Jws\\Parser] does not exist. at /home/ajzasssx/public_html/vendor/laravel/framework/src/Illuminate/Container/Container.php:879)
[stacktrace]
#0 /home/ajzasssx/public_html/vendor/laravel/framework/src/Illuminate/Container/Container.php(758): Illuminate\\Container\\Container->build('Imdhemy\\\\AppStor...')
#1 /home/ajzasssx/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(851): Illuminate\\Container\\Container->resolve('Imdhemy\\\\AppStor...', Array, false)
#2 /home/ajzasssx/public_html/vendor/laravel/framework/src/Illuminate/Container/Container.php(296): Illuminate\\Foundation\\Application->resolve('Imdhemy\\\\AppStor...', Array, false)
#3 /home/ajzasssx/public_html/vendor/laravel/framework/src/Illuminate/Container/Container.php(873): Illuminate\\Container\\Container->Illuminate\\Container\\{closure}(Object(Illuminate\\Foundation\\Application), Array)
#4 /home/ajzasssx/public_html/vendor/laravel/framework/src/Illuminate/Container/Container.php(758): Illuminate\\Container\\Container->build(Object(Closure))
#5 /home/ajzasssx/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(851): Illuminate\\Container\\Container->resolve('Imdhemy\\\\AppStor...', Array, true)
#6 /home/ajzasssx/public_html/vendor/laravel/framework/src/Illuminate/Container/Container.php(694): Illuminate\\Foundation\\Application->resolve('Imdhemy\\\\AppStor...', Array)
#7 /home/ajzasssx/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(836): Illuminate\\Container\\Container->make('Imdhemy\\\\AppStor...', Array)
#8 /home/ajzasssx/public_html/vendor/laravel/framework/src/Illuminate/Container/Container.php(1027): Illuminate\\Foundation\\Application->make('Imdhemy\\\\AppStor...')
#9 /home/ajzasssx/public_html/vendor/laravel/framework/src/Illuminate/Container/Container.php(947): Illuminate\\Container\\Container->resolveClass(Object(ReflectionParameter))
#10 /home/ajzasssx/public_html/vendor/laravel/framework/src/Illuminate/Container/Container.php(908): Illuminate\\Container\\Container->resolveDependencies(Array)
#11 /home/ajzasssx/public_html/vendor/laravel/framework/src/Illuminate/Container/Container.php(758): Illuminate\\Container\\Container->build('Imdhemy\\\\Purchas...')
#12 /home/ajzasssx/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(851): Illuminate\\Container\\Container->resolve('Imdhemy\\\\Purchas...', Array, false)
#13 /home/ajzasssx/public_html/vendor/laravel/framework/src/Illuminate/Container/Container.php(296): Illuminate\\Foundation\\Application->resolve('Imdhemy\\\\Purchas...', Array, false)
#14 /home/ajzasssx/public_html/vendor/laravel/framework/src/Illuminate/Container/Container.php(873): Illuminate\\Container\\Container->Illuminate\\Container\\{closure}(Object(Illuminate\\Foundation\\Application), Array)
#15 /home/ajzasssx/public_html/vendor/laravel/framework/src/Illuminate/Container/Container.php(758): Illuminate\\Container\\Container->build(Object(Closure))
#16 /home/ajzasssx/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(851): Illuminate\\Container\\Container->resolve('Imdhemy\\\\Purchas...', Array, true)
#17 /home/ajzasssx/public_html/vendor/laravel/framework/src/Illuminate/Container/Container.php(694): Illuminate\\Foundation\\Application->resolve('Imdhemy\\\\Purchas...', Array)
#18 /home/ajzasssx/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(836): Illuminate\\Container\\Container->make('Imdhemy\\\\Purchas...', Array)
#19 /home/ajzasssx/public_html/vendor/laravel/framework/src/Illuminate/Container/Container.php(1027): Illuminate\\Foundation\\Application->make('Imdhemy\\\\Purchas...')
#20 /home/ajzasssx/public_html/vendor/laravel/framework/src/Illuminate/Container/Container.php(947): Illuminate\\Container\\Container->resolveClass(Object(ReflectionParameter))
#21 /home/ajzasssx/public_html/vendor/laravel/framework/src/Illuminate/Container/Container.php(908): Illuminate\\Container\\Container->resolveDependencies(Array)
#22 /home/ajzasssx/public_html/vendor/laravel/framework/src/Illuminate/Container/Container.php(758): Illuminate\\Container\\Container->build('Imdhemy\\\\Purchas...')
#23 /home/ajzasssx/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(851): Illuminate\\Container\\Container->resolve('Imdhemy\\\\Purchas...', Array, true)
#24 /home/ajzasssx/public_html/vendor/laravel/framework/src/Illuminate/Container/Container.php(694): Illuminate\\Foundation\\Application->resolve('Imdhemy\\\\Purchas...', Array)
#25 /home/ajzasssx/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(836): Illuminate\\Container\\Container->make('Imdhemy\\\\Purchas...', Array)
#26 /home/ajzasssx/public_html/vendor/imdhemy/laravel-purchases/src/Handlers/HandlerFactory.php(52): Illuminate\\Foundation\\Application->make('Imdhemy\\\\Purchas...')
#27 /home/ajzasssx/public_html/vendor/imdhemy/laravel-purchases/src/Http/Controllers/ServerNotificationController.php(27): Imdhemy\\Purchases\\Handlers\\HandlerFactory->create()
```



And here the output of the composer


name     : imdhemy/appstore-iap
descrip. : PHP Appstore In-App Purchase implementation
keywords :
versions : * 1.1.0
type     : library
license  : MIT License (MIT) (OSI approved) https://spdx.org/licenses/MIT.html#licenseText
homepage :
source   : [git] https://github.com/imdhemy/appstore-iap.git a511a81dd6f13c9706762f1245ea2c0fb3026f93
dist     : [zip] https://api.github.com/repos/imdhemy/appstore-iap/zipball/a511a81dd6f13c9706762f1245ea2c0fb3026f93 a511a81dd6f13c9706762f1245ea2c0fb3026f93
path     : C:\wamp64\www\menassati-liap\vendor\imdhemy\appstore-iap
names    : imdhemy/appstore-iap

support
issues : https://github.com/imdhemy/appstore-iap/issues
source : https://github.com/imdhemy/appstore-iap/tree/1.02

autoload
psr-4
Imdhemy\AppStore\ => src/

requires
ext-json *
guzzlehttp/guzzle ^6.5|^7.4
nesbot/carbon ^2.51
php >=7.4

requires (dev)
fakerphp/faker ^1.15
friendsofphp/php-cs-fixer ^3.0
phpunit/phpunit ^9.5
roave/security-advisories dev-latest
symfony/var-dumper ^5.3
vimeo/psalm ^4.9

**Comment by imdhemy** [comment]
> Thanks for your quick response

My pleasure 🙌 

> name : imdhemy/appstore-iap
descrip. : PHP Appstore In-App Purchase implementation
keywords :
versions : * 1.1.0

The `Imdhemy\AppStore\Jws\Parser` was introduced in v [1.2.0](https://github.com/imdhemy/appstore-iap/releases/tag/1.2.0) 

Just make sure you are using the latest version of LIAP by running:

`composer require imdhemy/laravel-purchases -W`

Which will update the package and its dependencies.

**Comment by jadayash** [comment]
Thanks alot, fixed
