### ISSUE TITLE
Apple Server to Server Notification: Undefined index: original_application_version

### ISSUE THREAD

**Issue by drewjbartlett** [imdhemy/laravel-in-app-purchases#41]
**Describe the bug**
When an incoming server notification from Apple hits the endpoint I get an error about `original_application_version`. 

The route it hits is `purchase.serverNotifications.apple`.

**To Reproduce**
1. Make a purchase
2. Send incoming webhook (notification)
3. See error

**Expected behavior**
The notification should be parsed properly without an exception.

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
Here is the full trace:

```
production.ERROR: Undefined index: original_application_version {"exception":"[object] (ErrorException(code: 0): Undefined index: original_application_version at /app/vendor/imdhemy/appstore-iap/src/ValueObjects/Receipt.php:96)
[stacktrace]
#0 /app/vendor/imdhemy/appstore-iap/src/ValueObjects/Receipt.php(96): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /app/vendor/imdhemy/appstore-iap/src/Receipts/ReceiptResponse.php(73): Imdhemy\\AppStore\\ValueObjects\\Receipt::fromArray()
#2 /app/vendor/imdhemy/appstore-iap/src/Receipts/Verifier.php(59): Imdhemy\\AppStore\\Receipts\\ReceiptResponse->__construct()
#3 /app/vendor/imdhemy/appstore-iap/src/Receipts/Verifier.php(68): Imdhemy\\AppStore\\Receipts\\Verifier->verify()
#4 /app/vendor/imdhemy/laravel-purchases/src/Http/Rules/ValidReceipt.php(29): Imdhemy\\AppStore\\Receipts\\Verifier->verifyRenewable()
#5 /app/vendor/laravel/framework/src/Illuminate/Validation/Validator.php(736): Imdhemy\\Purchases\\Http\\Rules\\ValidReceipt->passes()
#6 /app/vendor/laravel/framework/src/Illuminate/Validation/Validator.php(548): Illuminate\\Validation\\Validator->validateUsingCustomRule()
#7 /app/vendor/laravel/framework/src/Illuminate/Validation/Validator.php(377): Illuminate\\Validation\\Validator->validateAttribute()
#8 /app/vendor/laravel/framework/src/Illuminate/Validation/Validator.php(408): Illuminate\\Validation\\Validator->passes()
#9 /app/vendor/laravel/framework/src/Illuminate/Validation/ValidatesWhenResolvedTrait.php(25): Illuminate\\Validation\\Validator->fails()
#10 /app/vendor/laravel/framework/src/Illuminate/Foundation/Providers/FormRequestServiceProvider.php(30): Illuminate\\Foundation\\Http\\FormRequest->validateResolved()
#11 /app/vendor/laravel/framework/src/Illuminate/Container/Container.php(1141): Illuminate\\Foundation\\Providers\\FormRequestServiceProvider->Illuminate\\Foundation\\Providers\\{closure}()
#12 /app/vendor/laravel/framework/src/Illuminate/Container/Container.php(1105): Illuminate\\Container\\Container->fireCallbackArray()
#13 /app/vendor/laravel/framework/src/Illuminate/Container/Container.php(1090): Illuminate\\Container\\Container->fireAfterResolvingCallbacks()
#14 /app/vendor/laravel/framework/src/Illuminate/Container/Container.php(711): Illuminate\\Container\\Container->fireResolvingCallbacks()
#15 /app/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(796): Illuminate\\Container\\Container->resolve()
#16 /app/vendor/laravel/framework/src/Illuminate/Container/Container.php(637): Illuminate\\Foundation\\Application->resolve()
#17 /app/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(781): Illuminate\\Container\\Container->make()
#18 /app/vendor/laravel/framework/src/Illuminate/Routing/RouteDependencyResolverTrait.php(79): Illuminate\\Foundation\\Application->make()
#19 /app/vendor/laravel/framework/src/Illuminate/Routing/RouteDependencyResolverTrait.php(48): Illuminate\\Routing\\ControllerDispatcher->transformDependency()
#20 /app/vendor/laravel/framework/src/Illuminate/Routing/RouteDependencyResolverTrait.php(28): Illuminate\\Routing\\ControllerDispatcher->resolveMethodDependencies()
#21 /app/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(41): Illuminate\\Routing\\ControllerDispatcher->resolveClassMethodDependencies()
#22 /app/vendor/laravel/framework/src/Illuminate/Routing/Route.php(239): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#23 /app/vendor/laravel/framework/src/Illuminate/Routing/Route.php(196): Illuminate\\Routing\\Route->runController()
#24 /app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(685): Illuminate\\Routing\\Route->run()
#25 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#26 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#27 /app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(687): Illuminate\\Pipeline\\Pipeline->then()
#28 /app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\\Routing\\Router->runRouteWithinStack()
#29 /app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(628): Illuminate\\Routing\\Router->runRoute()
#30 /app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(617): Illuminate\\Routing\\Router->dispatchToRoute()
#31 /app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\\Routing\\Router->dispatch()
#32 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#33 /app/vendor/spatie/laravel-http-logger/src/Middlewares/HttpLogger.php(28): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#34 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Spatie\\HttpLogger\\Middlewares\\HttpLogger->handle()
#35 /app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#36 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#37 /app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#38 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#39 /app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#40 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#41 /app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#42 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle()
#43 /app/vendor/fruitcake/laravel-cors/src/HandleCors.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#44 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle()
#45 /app/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#46 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle()
#47 /app/vendor/sentry/sentry-laravel/src/Sentry/Laravel/Tracing/Middleware.php(46): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#48 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Sentry\\Laravel\\Tracing\\Middleware->handle()
#49 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#50 /app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(140): Illuminate\\Pipeline\\Pipeline->then()
#51 /app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(109): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#52 /app/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle()
#53 {main}
"}
```

**Comment by drewjbartlett** [comment]
Also, as an aside, thank you a TON for all of your work on this. It saved me countless hours.

**Comment by michavie** [comment]
experiencing this as well, @drewjbartlett did you follow this

**Comment by michavie** [comment]
can follow PR in source package: https://github.com/imdhemy/appstore-iap/pull/6

**Comment by drewjbartlett** [comment]
Thanks a ton for this @michavie. I was going to make a PR this weekend so thank you for beating me to it.

**Comment by imdhemy** [comment]
Hi @drewjbartlett,
Sorry for the late reply, I was facing tough days!

Thanks, @michavie for the PR. It looks enough, except for the getter method I mentioned there.

**Comment by michavie** [comment]
@imdhemy no worries - getter is updated!

**Comment by drewjbartlett** [comment]
@imdhemy no worries - I know how life goes! Thanks for merging. Thanks again @michavie for the PR.
